#!/usr/bin/env bash
# install.sh — Set up the Tabelog Score Viewer native messaging host.
# Run once after cloning:  bash install.sh
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_DIR="$SCRIPT_DIR/.venv"
NATIVE_HOST="com.tabelog.proxy"
MANIFEST_FILE="$SCRIPT_DIR/com.tabelog.proxy.json"
MANIFEST_TEMPLATE="$SCRIPT_DIR/com.tabelog.proxy.json.example"
NATIVE_MANIFEST_DIR="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"

echo "=== Tabelog Score Viewer — Install ==="
echo "Repo: $SCRIPT_DIR"

# 1. Python venv
echo ""
echo "[1/4] Setting up Python venv..."
if ! command -v uv &> /dev/null; then
    echo "  Installing uv package manager..."
    curl -sSL https://astral.sh/uv/install.sh | bash
    export PATH="$HOME/.local/bin:$PATH"
fi
uv venv "$VENV_DIR"
uv pip install --python "$VENV_DIR/bin/python3" curl_cffi beautifulsoup4
echo "  Venv ready: $VENV_DIR"

# 2. Create wrapper script (machine-specific, gitignored)
echo ""
echo "[2/4] Creating launch wrapper..."
cat > "$SCRIPT_DIR/native_host.sh" << 'WRAPPER'
#!/bin/bash
# Generated by install.sh — do not commit
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/.venv/bin/activate"
exec python3 "$SCRIPT_DIR/native_host.py"
WRAPPER
chmod +x "$SCRIPT_DIR/native_host.sh"
echo "  Wrapper: $SCRIPT_DIR/native_host.sh"

# 3. Register with Chrome
echo ""
echo "[3/4] Registering with Chrome..."
mkdir -p "$NATIVE_MANIFEST_DIR"
sed "s|NATIVE_HOST_DIR|${SCRIPT_DIR}|" "$MANIFEST_TEMPLATE" > "$MANIFEST_FILE"
ln -sf "$MANIFEST_FILE" "$NATIVE_MANIFEST_DIR/$NATIVE_HOST.json"
echo "  Registered: $NATIVE_MANIFEST_DIR/$NATIVE_HOST.json -> $MANIFEST_FILE"

# 4. Done
echo ""
echo "[4/4] Done!"
echo ""
echo "Now load the extension in Chrome:"
echo "  1. chrome://extensions -> Developer mode ON"
echo "  2. Load unpacked -> select: $SCRIPT_DIR"
echo "  3. Browse tablecheck.com/ja/japan and hover over a restaurant"
